# -*- coding: utf-8 -*-
"""
    MANAGER -> BROKER -> WORKERS -> MONITOR -> SUBSCRIBER
"""

NUM_WORKERS = 0
ADDR = '127.0.0.1'
BROKER_IN_PORT  = '9011'
BROKER_OUT_PORT = '9012'

MONITOR_IN_PORT = BROKER_OUT_PORT
MONITOR_OUT_PORT = ""
